### ISSUE TITLE
"Cannot Create Window Surface"

### ISSUE THREAD

**Issue by thedigitalempress** [stephanh42/rpigl#4]
Hello,

I am currently trying to run your rpigl test on my raspberry pi and the stack trace keeps replying with "Cannot Create Window Surface". I am trying to create the spinning cube in chapter 6 of "Learning Python with Raspberry Pi."

**Comment by greigs** [comment]
same issue :(

```
pi@raspberrypi:~/rpigl/demos $ python pygametest.py 
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "pygametest.py", line 98, in <module>
    MyWindow(640, 480, pygame.RESIZABLE).run()
  File "/usr/local/lib/python2.7/dist-packages/rpigl/glesutils.py", line 906, in __init__
    window = create_opengl_window(width, height, flags)
  File "/usr/local/lib/python2.7/dist-packages/rpigl/rpi_egl.py", line 233, in create_opengl_window
    window = rpi_create_window(2, attribList)
  File "/usr/local/lib/python2.7/dist-packages/rpigl/rpi_egl.py", line 197, in rpi_create_window
    window.create_EGL_context(gl_version, attrib_list)
  File "/usr/local/lib/python2.7/dist-packages/rpigl/rpi_egl.py", line 169, in create_EGL_context
    raise Exception("cannot create window surface")
Exception: cannot create window surface

```

**Comment by greigs** [comment]
This worked... 
[https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate](https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate)

**Comment by thedigitalempress** [comment]
Thanks for finding this!! I'm going to get back to actually trying to fix it soon and give you an update on how it works.

**Comment by thedigitalempress** [comment]
I still got the error even after trying this fix. Are you running the same program as I am @greigs ?

**Comment by greigs** [comment]
@thedigitalempress Did you manage to get it working? Was it pygametest.py you were trying?

**Comment by thedigitalempress** [comment]
@greigs i did not unfortunately ): and yes. it involves using pygame but the piece of code isn't working to run the graphic.

**Comment by Kdevcode** [comment]
I am going through the same book and having the exact same issue. Did you ever get this figured out?
